# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'myBabyVaccineNote' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Then'
  pod 'SnapKit', '~> 5.0.0'
  pod 'DLRadioButton', '~> 1.4'
  pod 'KakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
  pod 'FSCalendar'
  # Pods for myBabyVaccineNote

end
