CREATE TABLE DISEASE_TABLE(
ID Int,
NAME VARCHAR(100)
);

INSERT INTO DISEASE_TABLE(ID, NAME)
VALUES (0, "대상포진");
INSERT INTO DISEASE_TABLE(ID, NAME)
VALUES (1, "로타바이러스");
INSERT INTO DISEASE_TABLE(ID, NAME)
VALUES (2, "A형간염");
INSERT INTO DISEASE_TABLE(ID, NAME)
VALUES (3, "수막구균");
INSERT INTO DISEASE_TABLE(ID, NAME)
VALUES (4, "사람유두종바이러스");
INSERT INTO DISEASE_TABLE(ID, NAME)
VALUES (5, "인플루엔자");
INSERT INTO DISEASE_TABLE(ID, NAME)
VALUES (6, "장티푸스");
INSERT INTO DISEASE_TABLE(ID, NAME)
VALUES (7, "Td(파상풍 / 디프테리아)");
INSERT INTO DISEASE_TABLE(ID, NAME)
VALUES (8, "폐렴구균");
INSERT INTO DISEASE_TABLE(ID, NAME)
VALUES (9, "수두");
INSERT INTO DISEASE_TABLE(ID, NAME)
VALUES (10, "Tdap(파상풍 / 디프테리아 / 백일해)");
INSERT INTO DISEASE_TABLE(ID, NAME)
VALUES (11, "신증후군출혈열");
