alter table VaccineAndHospital rename column column_0 to ID;
alter table VaccineAndHospital rename column column_1 to HOSPITAL_NAME;
alter table VaccineAndHospital rename column column_2 to DISEASE;
alter table VaccineAndHospital rename column column_3 to VACCINE;
alter table VaccineAndHospital rename column column_4 to PRICE;
alter table VaccineAndHospital rename column column_5 to LOCATION;
alter table VaccineAndHospital rename column column_6 to LATITUDE;
alter table VaccineAndHospital rename column column_7 to LONGITUDE;
alter table VaccineAndHospital rename column column_8 to SIDE_EFFECT;